language: python
os: linux
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8

notifications:
  email:
    on_success: change
    on_failure: always

env:
  jobs:
    - torch_v=">=1.4.0,<1.5.0" torchvision_v=">=0.5.0,<0.6.0"
    - torch_v=">=1.5.0,<1.6.0" torchvision_v=">=0.6.0,<0.7.0"
    - torch_v="" torchvision_v=""

before_install:
  - pip config set global.progress_bar off
  - sed -i s/^torch$/torch${torch_v}/ requirements.txt
  - sed -i s/^torchvision$/torchvision${torchvision_v}/ requirements.txt
  - sed -i s/^nnutils-pytorch$/nnutils-pytorch${torch_v}/ requirements.txt

install:
  - pip install "torch${torch_v}"
  - pip install -e ".[dev,test]"

script:
  - pre-commit run --all-files
  - pytest
