language: python
dist: xenial
sudo: true
python:
  - 3.5
  - 3.6
  - 3.7

notifications:
  email:
    on_success: change
    on_failure: always

env:
  matrix:
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.1.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.2.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.3.0.txt"
    - PYTORCH_REQUIREMENTS="requirements_pytorch_1.4.0.txt"
    - PYTORCH_REQUIREMENTS=""

before_install:
  # Upgrade PIP to latest version, in order to support --progres-bar
  - python -m pip install -U pip
  # Install dependencies for a particular PyTorch version first.
  - if [ -n "$PYTORCH_REQUIREMENTS" ]; then python -m pip install --progress-bar off -r travis/${PYTORCH_REQUIREMENTS}; fi
  - python -m pip install --progress-bar off -r requirements.txt

install:
  - python setup.py install

script:
  - ./travis/run_tests.sh
