language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - pip install cffi

install:
  - python setup.py install
  #- ./travis/build_nnutils.sh
  - ./travis/build_warp_ctc.sh

before_script:
  - pip install mypy

script:
  - ./travis/run_tests.sh
  - mypy --ignore-missing-imports --scripts-are-modules laia pylaia* | tee
