language: python
os: linux
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8

notifications:
  email:
    on_success: change
    on_failure: always

env:
  jobs:
    - torch_v=">=1.4.0,<1.5.0" torchvision_v=">=0.5.0,<0.6.0" nnutils_v=">=0.6.0,<0.7.0"
    - torch_v=">=1.5.0,<1.6.0" torchvision_v=">=0.6.0,<0.7.0" nnutils_v=""
    - torch_v="" torchvision_v="" nnutils_v=""

before_install:
  - pip config set global.progress_bar off
  - pip install "torch${torch_v}";
  - python -c "f = 'requirements.txt';
      r = open(f).read();
      r = r.replace('nnutils-pytorch\n', 'nnutils-pytorch${nnutils_v}\n');
      r = r.replace('torch\n', 'torch${torch_v}\n');
      r = r.replace('torchvision\n', 'torchvision${torchvision_v}\n');
      open(f, 'w').write(r);"

install: pip install -e ".[test]"

script: pytest
